# Pick macOS because that build environment has a never version of GnuPG than
# the Ubuntu ones.
os: osx

language: go
go:
  - 1.9
  - master

# Install the dependencies.
install:
  - go get -t -v ./...

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

before_script:
  - gpg-agent --homedir testdata/gnupg --daemon
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - go test -v -race ./...
